# Generated by Django 2.0.4 on 2018-04-22 14:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogArticles',
            new_name='BlogArticle',
        ),
    ]
